apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: airflow-on-k8s-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowbases
  - airflowbases/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowbases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowclusters
  - airflowclusters/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.k8s.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
# permissions to do edit airflowbases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflowbase-editor-role
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowbases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowbases/status
  verbs:
  - get
  - patch
  - update
---
# permissions to do viewer airflowbases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflowbase-viewer-role
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowbases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowbases/status
  verbs:
  - get
---
# permissions to do edit airflowclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflowcluster-editor-role
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowclusters/status
  verbs:
  - get
  - patch
  - update
---
# permissions to do viewer airflowclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflowcluster-viewer-role
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowclusters/status
  verbs:
  - get
---
